---
- name: Run susmit experiment
  gather_facts: no
  hosts: ['UCLA', 'WU']
  remote_user: ndnops

  roles: 
  - {role: 'ssh-ndnops-key-generate', tags: 'ssh'}
  - {role: '2023-susmit-ndndump', tags: 'ndntdump'}

