---
# tasks file for 2023-susmit-ndndump
- name: install docker
  apt:
    name: ['docker.io']

- name: build ndn6dump
  shell: sudo docker build -t ndn6dump 'github.com/yoursunny/ndn6dump#main'

- name: git ndntdump
  git: repo=https://github.com/tntech-ngin/capture-systemd.git
       dest=/home/ndnops/ndntdump
       update=yes
  register: gitclone

- command: ./setup.sh
  args:
    chdir: /home/ndnops/ndntdump
  when: gitclone.changed
